var g=UnityEngine.Object.FindAnyObjectByType<Afterecho.RunnerGame>();var touch=UnityEngine.InputSystem.Touchscreen.current;bool added=touch==null;if(added)touch=UnityEngine.InputSystem.InputSystem.AddDevice<UnityEngine.InputSystem.Touchscreen>();var mouse=UnityEngine.InputSystem.Mouse.current;
float volume=g.volume;g.volume=0;g.autoPlay=false;g.invincible=true;g.LabSeek(20);int step=0,before=0;double wall=0;var rows=new System.Collections.Generic.List<string>();
var pos=new UnityEngine.Vector2(UnityEngine.Screen.width*.5f,UnityEngine.Screen.height*.5f);
System.Action release=()=>{UnityEngine.InputSystem.InputSystem.QueueStateEvent(mouse,new UnityEngine.InputSystem.LowLevel.MouseState{position=pos});UnityEngine.InputSystem.InputSystem.QueueStateEvent(touch,new UnityEngine.InputSystem.LowLevel.TouchState{touchId=1,phase=UnityEngine.InputSystem.TouchPhase.Ended,position=pos});};
UnityEditor.EditorApplication.CallbackFunction tick=null;tick=()=>{try{
 if(g==null){UnityEditor.EditorApplication.update-=tick;if(added)UnityEngine.InputSystem.InputSystem.RemoveDevice(touch);return;}
 if(step==0&&g.Phase==Afterecho.GamePhase.Playing){before=g.AcceptedInputs;UnityEngine.InputSystem.InputSystem.QueueStateEvent(touch,new UnityEngine.InputSystem.LowLevel.TouchState{touchId=1,phase=UnityEngine.InputSystem.TouchPhase.Began,position=pos});UnityEngine.InputSystem.InputSystem.QueueStateEvent(mouse,new UnityEngine.InputSystem.LowLevel.MouseState{buttons=1,position=pos});wall=UnityEditor.EditorApplication.timeSinceStartup;step++;}
 else if(step==1&&UnityEditor.EditorApplication.timeSinceStartup-wall>.12){if(g.AcceptedInputs!=before+1)throw new System.Exception("touch then mouse duplicate");rows.Add("PASS touch then synthetic mouse is one contact");release();wall=UnityEditor.EditorApplication.timeSinceStartup;step++;}
 else if(step==2&&UnityEditor.EditorApplication.timeSinceStartup-wall>.2){before=g.AcceptedInputs;UnityEngine.InputSystem.InputSystem.QueueStateEvent(mouse,new UnityEngine.InputSystem.LowLevel.MouseState{buttons=1,position=pos});UnityEngine.InputSystem.InputSystem.QueueStateEvent(touch,new UnityEngine.InputSystem.LowLevel.TouchState{touchId=1,phase=UnityEngine.InputSystem.TouchPhase.Began,position=pos});wall=UnityEditor.EditorApplication.timeSinceStartup;step++;}
 else if(step==3&&UnityEditor.EditorApplication.timeSinceStartup-wall>.12){if(g.AcceptedInputs!=before+1)throw new System.Exception("mouse then touch duplicate");rows.Add("PASS mouse then touch is one contact");release();g.Menu();g.invincible=false;g.volume=volume;UnityEditor.EditorApplication.update-=tick;if(added)UnityEngine.InputSystem.InputSystem.RemoveDevice(touch);System.IO.File.WriteAllLines("PlaytestExports/Runner/live-contact-checks.txt",rows);}
}catch(System.Exception e){UnityEditor.EditorApplication.update-=tick;release();if(added)UnityEngine.InputSystem.InputSystem.RemoveDevice(touch);g.Menu();g.invincible=false;g.volume=volume;rows.Add("FAIL "+e.Message);System.IO.File.WriteAllLines("PlaytestExports/Runner/live-contact-checks.txt",rows);UnityEngine.Debug.LogError(e);}};UnityEditor.EditorApplication.update+=tick;return "contact checks queued";
