from pathlib import Path
import json
root=Path(__file__).resolve().parents[2]
p=root/'Builds/RunnerCircleWeb'
b=p/'Build'
loader=next(b.glob('*.loader.js')).name
pick=lambda ext:next(x.name for x in b.iterdir() if x.name.endswith(tuple(ext)))
config={'dataUrl':'Build/'+pick(['.data','.data.gz','.data.br','.data.unityweb']), 'frameworkUrl':'Build/'+pick(['.framework.js','.framework.js.gz','.framework.js.br','.framework.js.unityweb']), 'codeUrl':'Build/'+pick(['.wasm','.wasm.gz','.wasm.br','.wasm.unityweb']), 'streamingAssetsUrl':'StreamingAssets','companyName':'Gahee','productName':'잔향 AFTERECHO · RUNNER','productVersion':'runner-circle-v1','devicePixelRatio':1,'matchWebGLToCanvasSize':False}
html='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover"><title>잔향 AFTERECHO — 중앙 원 러닝 테스트</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#ffa321;font-family:system-ui,sans-serif}canvas{position:absolute;left:env(safe-area-inset-left,0px);top:env(safe-area-inset-top,0px);display:block;width:calc(100% - env(safe-area-inset-left,0px) - env(safe-area-inset-right,0px));height:calc(100% - env(safe-area-inset-top,0px) - env(safe-area-inset-bottom,0px));touch-action:none;outline:none}#loading{position:fixed;inset:0;display:grid;place-content:center;text-align:center;color:#101117;gap:12px;font-weight:700;letter-spacing:.1em}progress{width:240px;height:6px;accent-color:#101117}#error{position:fixed;inset:20%;padding:30px;background:#111;color:#fff;display:none;white-space:pre-wrap}</style><canvas id="unity-canvas" tabindex="0" aria-label="잔향 리듬 러닝 게임"></canvas><div id="loading"><div>잔향 AFTERECHO</div><small>RUNNER CIRCLE · TEAM TEST</small><progress max="1" value="0"></progress></div><div id="error"></div><script src="Build/LOADER"></script><script>const canvas=document.querySelector('canvas');canvas.width=Math.max(1,Math.round(canvas.clientWidth));canvas.height=Math.max(1,Math.round(canvas.clientHeight));const config=CONFIG;config.preRun=[module=>{module.SystemInfo.width=canvas.width;module.SystemInfo.height=canvas.height;}];createUnityInstance(canvas,config,p=>document.querySelector('progress').value=p).then(instance=>{window.afterechoUnity=instance;const fit=()=>{const w=Math.round(canvas.clientWidth),h=Math.round(canvas.clientHeight);instance.Module.SystemInfo.width=w;instance.Module.SystemInfo.height=h;if(canvas.width!==w)canvas.width=w;if(canvas.height!==h)canvas.height=h;instance.SendMessage('Afterecho_RunnerCircle','ResizeViewport',w+','+h);};fit();new ResizeObserver(fit).observe(canvas);window.addEventListener('resize',fit);document.querySelector('#loading').remove();canvas.focus();}).catch(e=>{const box=document.querySelector('#error');box.style.display='block';box.textContent='게임을 불러오지 못했습니다. 실행 안내의 로컬 서버로 열어주세요.\\n'+e;});document.addEventListener('contextmenu',e=>e.preventDefault());</script></html>'''.replace('LOADER',loader).replace('CONFIG',json.dumps(config,ensure_ascii=False))
(p/'index.html').write_text(html)
print('Responsive launcher written',config)
